/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzz_jniproject_MainActivity */

#ifndef _Included_com_zzz_jniproject_MainActivity
#define _Included_com_zzz_jniproject_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzz_jniproject_MainActivity
 * Method:    testJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zzz_jniproject_MainActivity_testJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
